name: 'Pull Request Workflow'

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]

jobs:
  assign-reviewers1:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Add Pull Request Reviewer
        uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with: 
          reviewers: "kmalmlov,RohitGoyani"
          token: ${{ secrets.GITHUB_TOKEN }}