name: 'Pull Request Workflow'

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]

jobs:
  add-review:
    uses: 'SaaS-Innova/github-action/.github/workflows/auto_assign.yml@main'
    with:
      configuration_path: '.github/auto_assign.yml'
  